[build]
target = ["armv7-unknown-linux-gnueabihf","x86_64-unknown-linux-gnu"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "cc"
